name: brick
description: A simple state management library for Flutter
version: 0.0.1
repository: https://github.com/joranmulderij/brick
homepage: https://github.com/joranmulderij/brick

environment:
  sdk: ^3.3.0

dependencies:
  meta: ^1.10.0
  very_good_analysis: ^5.1.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
